# fly.toml app configuration file generated for real-estate-roi-app on 2025-09-15T20:48:31-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'real-estate-roi-app'
primary_region = 'ord'

[build]

[deploy]
  release_command = 'bash scripts/deploy-db.sh'

[env]
  DATABASE_URL = 'file:/data/production.db'
  NODE_ENV = 'production'
  NEXT_PUBLIC_APP_NAME="Investment Property Calculator"
  NEXT_PUBLIC_APP_VERSION="1.0.0"

  DEFAULT_INTEREST_RATE=7.5
  DEFAULT_LOAN_TERM=30
  DEFAULT_VACANCY_RATE=0.05
  DEFAULT_CAP_RATE_THRESHOLD=6.0
  DEFAULT_ROI_THRESHOLD=8.0

  NEXTAUTH_SECRET='your-strong-random-secret'
  NEXTAUTH_URL='https://real-estate-roi-app.fly.dev'
  ADMIN_EMAIL='dareljohnson@gmail.com'

  # Redacted – set these via Fly secrets or build args, not committed plaintext
  GOOGLE_MAPS_API_KEY="your-api-key"
  NEXT_PUBLIC_GOOGLE_PLACES_API_KEY="your-api-key"

  DEPLOY_RUN_MIGRATIONS=true  # (default: true)
  DEPLOY_RUN_SEED=false       # (default: true)

  SEED_ADMIN_EMAIL="admin@example.com"
  SEED_ADMIN_PASSWORD="StrongPass123!"
  SEED_ADMIN2_EMAIL="second.admin@example.com"
  SEED_ADMIN2_PASSWORD="AnotherStrongPass!"    # optional

[[mounts]]
  source = 'database_vol'
  destination = '/data'
  snapshot_retention = 14
  auto_extend_size_threshold = 80
  auto_extend_size_increment = "1GB"
  auto_extend_size_limit = "5GB"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 4
